### ISSUE TITLE
TypeError: position_data.filter is not a function

### ISSUE THREAD

**Issue by spammik** [lagoanova/Binance-Futures-Signals#1]
Hello,

I filled all the required parameters and when I do **npm start** - after a while, it will show the following error :
```
TypeError: position_data.filter is not a function
    at checkOrders (D:\futuresky\Binance-Futures-Signals\index.js:304:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I did everything according to the instructions, I do not know where the mistake may be.

![image](https://user-images.githubusercontent.com/57185483/165532012-a32da85b-abd0-42b7-b04c-2e42bb89ce5c.png)

Thanks.

**Comment by ghostnetrn** [comment]
Sign up to [Binance Futures](https://www.binance.com/)
Log into your Binance account and go to the account settings -> API Management page where you can create a new API key.
For the API restrictions, make sure 'Eanable reading', and 'Enable Futures' are enabled. Make sure 'Enable Withdrawals' is disabled.

**Comment by spammik** [comment]
> 

My API key and secret is OK I guess - take a look.

![image](https://user-images.githubusercontent.com/57185483/165732830-62d0d389-5da5-4703-b6b6-116bb23360b6.png)

**Comment by ghostnetrn** [comment]
Install nodejs version 14 or 16

**Comment by ghostnetrn** [comment]
https://nodejs.org/en/blog/release/v14.17.3/
